# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b55f49bc5c4a38d7b74a38f861aec5fdb3517867217c8f8335e90bbf700f3cbcd6d1441ec18dbe2208918244c683750c22db062436aafd4271122d88249d854

test:
  secret_key_base: 1994cfe19a203c9e0d261490818b9f021b23c3a1ba180e1fec25e81cbc3ab626822c9d4d3da4678f8121d3b6f73a9da0da8a415ab2518ae048604148c2562e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
